[build]
  # Memberitahu Netlify di mana letak function-nya
  functions = "netlify/functions"

[functions]
  # Memaksa Netlify menyertakan semua file di dalam folder views dan public ke dalam serverless function
  included_files = ["src/views/**", "src/public/**", "node_modules/.prisma/client/**", "prisma/schema.prisma"]

[[redirects]]
  # Mengarahkan semua traffic pengunjung ke function 'api' yang memuat Express
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200